<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dimasiks-MacBook-Pro.local" failures="12" tests="23" name="CalculatorFunctionality" time="28.373" errors="0" timestamp="2021-08-11T23:31:15 EDT">
  <testcase classname="tests.CalculatorFunctionalityTest" name="addTest" time="0.24">
    <failure type="java.lang.AssertionError" message="expected [6] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [7]
at tests.CalculatorFunctionalityTest.addTest(CalculatorFunctionalityTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- addTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="addTest" time="0.208"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="addTest" time="0.213"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="addTest" time="0.205"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="addTest" time="0.197"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="subtractTest" time="0.189">
    <failure type="java.lang.AssertionError" message="expected [-4] but found [-5]">
      <![CDATA[java.lang.AssertionError: expected [-4] but found [-5]
at tests.CalculatorFunctionalityTest.subtractTest(CalculatorFunctionalityTest.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- subtractTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="subtractTest" time="0.208"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="subtractTest" time="0.192"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="subtractTest" time="0.206"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="subtractTest" time="0.184"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="multiplyTest" time="0.227">
    <failure type="java.lang.AssertionError" message="expected [5] but found [8]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [8]
at tests.CalculatorFunctionalityTest.multiplyTest(CalculatorFunctionalityTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- multiplyTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="multiplyTest" time="0.205">
    <failure type="java.lang.AssertionError" message="expected [8] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [10]
at tests.CalculatorFunctionalityTest.multiplyTest(CalculatorFunctionalityTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- multiplyTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="multiplyTest" time="0.192">
    <failure type="java.lang.AssertionError" message="expected [27] but found [29]">
      <![CDATA[java.lang.AssertionError: expected [27] but found [29]
at tests.CalculatorFunctionalityTest.multiplyTest(CalculatorFunctionalityTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- multiplyTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="multiplyTest" time="0.192">
    <failure type="java.lang.AssertionError" message="expected [56] but found [58]">
      <![CDATA[java.lang.AssertionError: expected [56] but found [58]
at tests.CalculatorFunctionalityTest.multiplyTest(CalculatorFunctionalityTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- multiplyTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="multiplyTest" time="0.197">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at tests.CalculatorFunctionalityTest.multiplyTest(CalculatorFunctionalityTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- multiplyTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="divideTest" time="0.188">
    <failure type="java.lang.AssertionError" message="expected [0.2] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [0.2] but found [0]
at tests.CalculatorFunctionalityTest.divideTest(CalculatorFunctionalityTest.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- divideTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="divideTest" time="0.245">
    <failure type="java.lang.AssertionError" message="expected [0.5] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0.5] but found [1]
at tests.CalculatorFunctionalityTest.divideTest(CalculatorFunctionalityTest.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- divideTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="divideTest" time="0.201"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="divideTest" time="0.189">
    <failure type="java.lang.AssertionError" message="expected [0.875] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0.875] but found [1]
at tests.CalculatorFunctionalityTest.divideTest(CalculatorFunctionalityTest.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- divideTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="divideTest" time="0.196"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="changeActionTest" time="2.353">
    <failure type="java.lang.AssertionError" message="expected [1.01] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [1.01] but found [1]
at tests.CalculatorFunctionalityTest.changeActionTest(CalculatorFunctionalityTest.java:118)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- changeActionTest -->
  <testcase classname="tests.CalculatorFunctionalityTest" name="floatingPointTest" time="2.301"/>
  <testcase classname="tests.CalculatorFunctionalityTest" name="clearButtonTest" time="0.407">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [123456789] but found [123466789]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [123456789] but found [123466789]
at tests.CalculatorFunctionalityTest.clearButtonTest(CalculatorFunctionalityTest.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- clearButtonTest -->
</testsuite> <!-- CalculatorFunctionality -->
